# -*- coding: utf-8 -*-
"""amazonbestseller_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWCdaaTqqWWcYW7HP3v8WPLQCqACZeF3
"""

#from google.colab import files
#bestsellers = files.upload()

import pandas as pd
df = pd.read_csv('bestsellers_with_categories.csv')
display(df)

print(df.head())

print(df.shape) #output means 5 rows by 7 columns
display(df.shape)

print(df.columns)

print(df.describe())

df.drop_duplicates(inplace=True)#inplace true will modify og df
display(df)

df.rename(columns={"Name": "Title", "Year":"Publication Year", "User Rating": "Rating"},inplace=True)
display(df)

df["Price"] = df["Price"].astype(float)
display(df)

#-------------df now ready for analysis--------------------#
author_counts = df['Author'].value_counts()
print(author_counts)

avg_rating_by_genre = df.groupby('Genre')['Rating'].mean()
print(avg_rating_by_genre)

author_counts.head(10).to_csv("top_authors.csv") #export top selling authors to csv

avg_rating_by_genre.to_csv("avg_rating_by_genre.csv") #export avg rating by genre to csv

dfcounts = pd.read_csv('top_authors.csv')
dfratings = pd.read_csv('avg_rating_by_genre.csv')
display(dfcounts)
display(dfratings)

#goals achieved
# Imported book data about the top 50 books on Amazon from 2009 to 2019.
# Explored and cleaned the data with DataFrame methods.
#Exported the modified data to a new CSV file.

#tutorial from : https://www.codedex.io/projects/analyze-spreadsheet-data-with-pandas-chatgpt
